nyaadevs/nyaa

trackers.txt

It's dead for long time already.

Openbittorrent -> Opentrackr

---

nyaa/templates/layout.html

There was a simple problem with dictionary field name.

Fixed problem with saving filter after reloading (#26)

---

nyaa/__init__.py
nyaa/templates/layout.html

Display the site's commit hash

---

nyaa/static/js/main.js
nyaa/templates/layout.html
nyaa/templates/view.html

As per title. Eliminates potential XSS issues, plus CommonMark in general is a good idea.

Switch marked to commonmark

---

nyaa/static/css/main.css

Fixes this issue ![](https://imgoat.com/uploads/0efdf2ec9b/16939.PNG) pointed on on the IRC

Fix torrent view text overflowing

---

nyaa/static/css/main.css
nyaa/static/js/main.js
nyaa/templates/upload.html

As requested in #99 
The drag & drop currently allows for multiple files to be added, but the Browse button doesn't (even though the JS code looks to be setup to handle multiple files)
What should it be?
Preview:

Drag&Drog torrent file in upload

---

nyaa/api_handler.py
nyaa/backend.py
nyaa/routes.py
utils/api_uploader.py

Updated api/upload to use code in backend.py
Cleaned up api_uploader.py

Updated api/upload

---

nyaa/forms.py

replaced deprecated Classes by their newer versions

replaced deprecated Classes by their newer versions

---

nyaa/api_handler.py
nyaa/models.py
nyaa/routes.py
utils/api_uploader_v2.py

Wrote a new upload endpoint and a script with `argparse`'d arguments.
Currently routed (with a Blueprint) to `/api/v2/upload`.

Upload API V2

---

nyaa/api_handler.py
utils/api_uploader.py

Fixed possible crash in api_handler.py

Fixed possible crash in api_handler.py

---

nyaa/routes.py
nyaa/templates/profile.html

1. Changed page title to "Profile of {{ USERNAME }}"
2. User information is now shown at page top (not inside one of the tabs)

Make profile page more profile

---

config_es_sync.json
sync_es.py

the old synchronous io was too slow apparently. now threads. vary nice.

sync_es: multithread so it can actually keep up

---

nyaa/static/css/main.css

#145 
Used #1d4568 instead of the suggested #dd77ff though www

Issue #145: Added CSS change for visited links

---

nyaa/models.py
nyaa/routes.py

Apply PEP8

---

nyaa/templates/user.html

Even though only mods/admins can see it.
Currently it just uses the default avatar.

Use gravatar URL in /user/<username>

---

nyaa/static/css/main.css
nyaa/static/js/main.js
nyaa/templates/layout.html
nyaa/templates/view.html

This was on my agenda since #66. @TheAMM 
**Notes:**
* I tried to keep jQuery/JS usage to the minimum.
* I also tried my best to make the [HTML source code look reasonable](https://cloud.githubusercontent.com/assets/10238474/26446389/772fc234-414c-11e7-95d0-96454b1310c8.png) with that Jinja2 loop...
* I don't feel like it's the best design, so suggestions are very welcome!
* Perhaps titles should be added to the anchors? "Collapse this folder", or something like that?
**Preview:** (3.3mb gif, sorry)

Basic collapsible file tree

---

nyaa/static/css/main.css
nyaa/templates/view.html

@TheAMM
***
No need for another CSS version since the last one didn't go live just yet.

Strip collapse functionality from file list panel

---

nyaa/routes.py
nyaa/templates/view.html

Example: https://nyaa.si/view/535778
**Before:**
**After:**

Fix inverted icons in file list

---

nyaa/search.py
nyaa/static/css/main.css
nyaa/templates/search_results.html

Partially related to #172.
Will only show when number of comments is above zero.
**Current preview:** // ([old](https://cloud.githubusercontent.com/assets/10238474/26455698/a986893a-4173-11e7-9868-4b84874c8fa3.png))

Add number of comments to torrent lists

---

requirements.txt

It could also be possible that I'm the only one having this issue...
I'm using Debian Jessie for this.

Fix progressbar33 while fetching requirements

---

sync_es.py

Fixes the process just idling when something goes wrong in a thread.

sync_es: die when killed

---

nyaa/templates/search_results.html

As mentioned in https://github.com/nyaadevs/nyaa/issues/212 I also think the proposed titles are better.

Replace the header titles

---

.travis.yml
README.md
lint.sh
nyaa/models.py
nyaa/search.py
utils/api_uploader_v2.py

* Include utils/ in lint checker(s)
* Fix PEP8 warnings/errors
* Update `lint.sh` to have arguments:
```
$ ./lint.sh -h
Lint checker/fixer
Usage: ./lint.sh [-c|--check] [-h|--help]
No arguments : Check and auto-fix some warnings/errors
-c | --check : only check lint (don't auto-fix)
-h | --help  : show this help and exit
```
* Update Travis config

Fix lint check + update lint script

---

nyaa/static/js/main.js

Autoconvert URL-like text to links

Enable `linkify` for Markdown parser

---

nyaa/templates/view.html

Hide "Report" button for site guests

---

nyaa/routes.py

* Fix [`url referenced before assignment.`](https://user-images.githubusercontent.com/10238474/27862507-2c946e02-618e-11e7-8e37-a26e9401201a.png)
* Fix every action logged as delete/undelete
* Use `editor` var (defined but not used) instead of `flask.g.user`
@mreweilk

Fix torrent deletion log

---

nyaa/models.py
nyaa/routes.py
nyaa/templates/user.html

I also converted the user template to tabs since it was still spaces.

Add logging for reports, user bans for super admins

---

nyaa/api_handler.py
nyaa/backend.py
nyaa/routes.py
nyaa/search.py
nyaa/template_utils.py
nyaa/templates/adminlog.html
nyaa/templates/edit.html
nyaa/templates/layout.html
nyaa/templates/reports.html
nyaa/templates/rss.xml
nyaa/templates/search_results.html
nyaa/templates/view.html
nyaa/utils.py
nyaa/views/__init__.py
nyaa/views/account.py
nyaa/views/admin.py
nyaa/views/main.py
nyaa/views/site.py
nyaa/views/torrents.py
nyaa/views/users.py
setup.cfg
tests/test_template_utils.py

1. [#269 - Import sorting + Static pages](https://github.com/nyaadevs/nyaa/pull/269)
2. [#292 - Move account routes into blueprint](https://github.com/nyaadevs/nyaa/pull/292)
3. [#295 - Move admin routes into blueprint](https://github.com/nyaadevs/nyaa/pull/295)
4. [#300 - Move user routes into blueprint](https://github.com/nyaadevs/nyaa/pull/300)
5. [#301 - Move template filters and globals into blueprint](https://github.com/nyaadevs/nyaa/pull/301)
6. [#303 - Move home, RSS and request handlers into blueprint](https://github.com/nyaadevs/nyaa/pull/303)
7. [#306 - Move torrent routes into blueprint](https://github.com/nyaadevs/nyaa/pull/306)
8. [#307 - Finish routes.py restructuring process](https://github.com/nyaadevs/nyaa/pull/307)
Adding the following changes from `master`:
(sorted by …

Refactor routes.py into blueprints

---

lint.sh
nyaa/__init__.py
nyaa/api_handler.py
nyaa/backend.py
nyaa/fix_paginate.py
nyaa/forms.py
nyaa/models.py
nyaa/search.py
nyaa/torrents.py
nyaa/utils.py
nyaa/views/__init__.py
requirements.txt
setup.cfg

**Update:**
Added isort to the lint checking process and script,
so after this merges, you'll need to install `isort` in your virtual env.
1. Applied import sorting (isort) to all `*.py` files in `nyaa/` (recursively).
2. Fixed the following Flake8-reported issues:
- `nyaa\__init__.py`:
- `nyaa\api_handler.py`:
~**I didn't fix this one, because I've yet to check why it was assigned to a var in the first place.**~
I just disabled the check for this line, because `/ghetto_import` is temporary.
- `nyaa\backend.py`:
- `nyaa\fix_paginate.py`:
_@TheAMM_
**I'm not sure, was it imported for a reason? It seems to work just fine without it.**
- `nyaa\forms.py`:
- `nyaa\models.py`:
- `nyaa\search.py`:
- `nyaa\torrents.py`:

Apply isort & flake8

---

nyaa/backend.py
nyaa/forms.py
nyaa/models.py
nyaa/templates/edit.html
nyaa/views/torrents.py

Add banning torrents for moderators which disallows reuploading.
New delete UI.
Fixes #39

Expose soft delete to users and allow reuploading of deleted torrents. (fixes #39)

---

nyaa/templates/help.html

Some people may not realise that they can do this themselves, and maybe they'll consult the help page before abusing the report button.

help page: Add help for deletion

---

migrations/versions/500117641608_add_bans.py
nyaa/__init__.py
nyaa/forms.py
nyaa/models.py
nyaa/static/css/main.css
nyaa/static/js/main.js
nyaa/template_utils.py
nyaa/templates/admin_bans.html
nyaa/templates/adminlog.html
nyaa/templates/edit.html
nyaa/templates/layout.html
nyaa/templates/user.html
nyaa/views/account.py
nyaa/views/admin.py
nyaa/views/main.py
nyaa/views/torrents.py
nyaa/views/users.py

Better bans

---

nyaa/backend.py

Currently just rejects torrents with RTL overrides in filenames.
Can be extended to reject uncommon (Windows-restricted) characters as well `?<>\:|"` and whatnot), or restricted (Windows) filenames (`NULL`, `COM`?)
Closes #330.

Early filename validation

---

nyaa/static/css/main.css
nyaa/static/js/main.js
nyaa/templates/layout.html

`why doesn't the meme cartel have anyone good at css?`
addresses issue #28

Improve dark theme

---

nyaa/template_utils.py

#405 
Updating the search query parameters should reset to the first page

reset page when updating search parameters

---

nyaa/templates/register.html

More than enough users have their verification emails lost thanks to Outlook/Hotmail shenanigans.
----

Alert hotmail users of the void on register page

---

config.example.py
nyaa/forms.py

[Config change] Email blacklist

---

nyaa/models.py
nyaa/templates/user.html
nyaa/templates/user_comments.html
nyaa/views/users.py

Quick and dirty comment list for moderators to look at

---

nyaa/templates/_formhelpers.html
nyaa/templates/user.html

Properly scaffold it, remove a superfluous form-group div, and style the select properly.

user: clean up admin_form HTML

---

nyaa/forms.py
nyaa/templates/view.html

Untangled this from the other PR because you wanted this right now

commenting: show CAPTCHA to new accounts

---

nyaa/static/css/main.css
nyaa/templates/reports.html

* comment edit button
* border around "selected" comment
* minor fixes to the admin > reports page

Update dark theme

---

.gitignore
info_dicts/.gitignore
migrations/versions/b61e4f6a88cc_del_torrents_info.py
nyaa/api_handler.py
nyaa/backend.py
nyaa/models.py
nyaa/torrents.py
nyaa/views/torrents.py
torrent_cache/.gitignore
torrents/.gitignore
utils/infodict_mysql2file.py

Move bencoded info dicts from mysql torrent_info table to info_dict directory.
DB change!
IMPORTANT!!! Make sure to run utils/infodict_mysql2file.py before upgrading the database.

Move bencoded info dicts from mysql torrent_info table to info_dict directory.

---

nyaa/templates/user.html

Change each ban to be a bullet point in an unordered list.

Fix user page ban list styling for multiple bans

---

migrations/versions/ecb0b3b88142_flags2columns.py
nyaa/models.py
nyaa/search.py
sync_es.py

improves mysql performance through indexes
should work fine™ but more testing would be appropriate before deploying
also tracker needs to be changed
somewhat finished, however:
- elasticsearch integration is not tested
- didn't benchmark everything

[Schema change] Torrents flags bitflag column to indexed columns

---

nyaa/static/js/main.js
nyaa/templates/help.html
nyaa/templates/view.html

comments: fix editing for users with a CAPTCHA

---

nyaa/templates/user.html
nyaa/torrents.py

Hope I did it right. Will automatically disable itself if any search is done.

Add torrent counter on profile page (#409)

---

nyaa/backend.py

Windows has a few special filenames that it does not allow the explorer.exe and command line to see, but can still be created by applications. This is due to some jank DOS compatibility.
These filenames can be abused to troll Windows users, so we should probably blacklist them.

backend: blacklist Windows reserved filenames

---

nyaa/templates/rss.xml
nyaa/templates/xmlns.html

Add amount of comments to RSS

---

nyaa/__init__.py
nyaa/template_utils.py

```
This commit adds a caching_url_for using functools.lru_cache (currently
with maxsize at 4096 entries) and replaces flask.url_for with it, as
there is no harm in doing so.
This greatly improves template generation speed, from ~115ms to ~75ms on
the front page (using the simple benchmark introduced in the previous
commit).
```
Some benchmarks:
Git master:
```
Page   1: min:108.9ms max:137.8ms avg:120.7ms
Page   2: min:105.3ms max:137.1ms avg:114.6ms
Page   3: min:103.9ms max:130.1ms avg:114.2ms
Page   4: min:103.3ms max:143.1ms avg:117.4ms
Page   5: min:100.3ms max:136.0ms avg:115.5ms
Page   6: min:108.5ms max:146.1ms avg:119.0ms
Page   7: min:110.0ms max:150.8ms avg:119.5ms
Page   8: min:103.2ms max:154.8ms avg:118.1ms
Page   9: min:103.8ms max:132.5ms avg:116.6ms
Page  10: min:103.5ms …
```

Cache url_for calls with lru_cache

---

nyaa/extensions.py
nyaa/search.py
nyaa/templates/user.html

* Fix the upload count on user pages to not be limited by the page maximum
* Allow users to bypass the page maximum if they're logged in

Query limit fixes

---

nyaa/forms.py
nyaa/models.py
nyaa/template_utils.py
nyaa/templates/user.html
nyaa/views/users.py

Add Nuke Comments button to user profile Danger Zone.
Deletes all of the users comments from both sites.

nuke comments

---

nyaa/search.py

search: allow admins to ignore the max page limit

---

create_es.sh
es_mapping.yml
import_to_es.py
nyaa/templates/search_results.html
nyaa/views/main.py
sync_es.py

i got it to work on my machine, including the binlog thing. Nothing major appears to have changed besides their mapping syntax and the type removal thing. Maybe there are better search features now though, I'd check the changelog at some point
https://www.elastic.co/blog/elasticsearch-7-0-0-released
https://www.elastic.co/blog/elasticsearch-6-0-0-released

elasticsearch 7.x compatability
