nyaadevs/nyaa

nyaa/templates/rss.xml
Might cause issues for applications with an XML parser that considers leading and trailing whitespace characters as significant. Encountered and fixed this issue in my application, sending this PR in case it affects others.
=> Remove whitespace from RSS links

nyaa/static/css/main.css
Made it so that the torrent info is a bit easier to read on the compact version.
- [Mobile before](http://i.imgur.com/L6TyR3h.png)    
- [Mobile after](http://i.imgur.com/euutdTJ.png)
Also removed the slightly gray background on odd numbered torrents on the list.
=> Small CSS tweaks to the torrent listing and torrent view on mobile

nyaa/static/css/main.css
Please check if this breaks something
before: http://i.imgur.com/cI1pZrF.png
after: http://i.imgur.com/BIC722K.png
=> Fix layout on long torrent names

nyaa/static/css/main.css
There does not seem to be a css class that marks the theme, so not sure how is the proper bootstrap way to fix this.
Also, the "remake" and "trusted" colors should be changed in nightmode as well, to a darker tone.
Current: http://i.imgur.com/hDNv7nf.png
After: http://i.imgur.com/upLHArx.png
=> Revert c14649b because it "breaks" nightmode

nyaa/static/css/main.css, nyaa/static/js/main.js, nyaa/templates/_formhelpers.html, nyaa/templates/edit.html, nyaa/templates/upload.html
In order to make the markdown editor fields reusable, I've added a `render_markdown_editor` macro that should automatically generate the relevant DOM structure which is utilised by the changes in `main.js`. To make sure that we can multiple markdown editors, you have to namespace them with the field's name.
Let me know you would like any further changes.
=> Markdown preview

nyaa/routes.py, nyaa/templates/view.html
This is very, very simple, based on the table that currently exists.
Ideally, it should be done using `<li>` & `<ul>`, and allow for collapsing every directory tree (separately).
But I don't think I'm capable of doing that.
This configuration should be good in the meantime.
**Preview:**
=> Improve file list

nyaa/templates/search_results.html
When torrent name is very short (and is the only result), the link column gets too wide.
Setting an optimal width of 70px fixes this.
**Before:** (https://nyaa.si/?q=170513+PV+BATCH&f=0&c=0_0)
**After:**
=> Fix 'Link' column header width

nyaa/templates/search_results.html
Removed my old PR #74 because it had become a mess.
---
To solve a problem pointed out by someone in the IRC.
User could not read the full name of the torrent
So this will allow the full name to appear on mouseover.
----
**I'll just ask someone to test, since I don't actually have the project and database set up.**
=> Add full torrent name to link "title"

nyaa/templates/upload.html
=> Put tracker URL in <kbd>

nyaa/templates/view.html
Same thing as I did for the directories on the first level of the tree.
**Before:** (https://nyaa.si/view/923330)
**After:**
=> Fix padding for single file in torrent file list

nyaa/__init__.py, nyaa/api_handler.py, nyaa/backend.py, nyaa/fix_paginate.py, nyaa/forms.py, nyaa/models.py, nyaa/routes.py, nyaa/search.py, nyaa/torrents.py
**Fixes:**
* E501 line too long
* E265 block comment should start with '# '
* E266 too many leading '#' for block comment
* E713	test for membership should be ‘not in’
**Note:**
I also changed some logic in `api_handler.py`
1. https://github.com/nyaadevs/nyaa/pull/53/commits/a3710ae315069880b4922977be07ed50145ab65e#diff-81eaa857cacfa258a7a0040bbdb1dd7bR128
2. https://github.com/nyaadevs/nyaa/pull/53/commits/a3710ae315069880b4922977be07ed50145ab65e#diff-81eaa857cacfa258a7a0040bbdb1dd7bR186
**Ignored errors:**
* [nyaa/__init__.py:56:1:](https://github.com/nyaadevs/nyaa/pull/53/commits/1734eb3b846f9b2dfe59b7c6e1c2998d66ab8f02) E402 module level import not at top of file
=> Fix PEP8 errors and warnings

nyaa/static/css/main.css, nyaa/templates/layout.html
These changes make sure that the mobile search bar is usable on mobile devices or widths. Unfortunately, since we are using Bootstrap select which is a Bootstrap extension, it adjusts the width of the fields via JavaScript which is awfully shit.
I don't particularly want to use `!important` in CSS since that's equally as terrible. Let me know if you would any further changes and comments.
=> Issue #35: Mobile search improvements

nyaa/templates/layout.html
SRI means that there's a lesser risk for XSS, and cdnjs itself recommends always requesting them over HTTPS [in their "About" page](https://cdnjs.com/about). Switching the bootstrap JS over to using cdnjs also means there's one less third party involved.
=> Use cdnjs with SRI and HTTPS for all CDN JS files

nyaa/routes.py, nyaa/templates/rss.xml
This is intended to fix #34, and also for other auto-downloaders (SickBeard/SickRage/Medusa/etc.)
(**Supersedes #31**)
* Refactor:
* Only check `if torrent.has_torrent` for the `<link>` element.
* Add elements:
* description
* category (formatted as `main_category - sub_category`)
* size (formatted size) ~_**(in bytes)**_ **I wasn't sure what's better** - size in bytes or formatted size?~
* seeders
* leechers
* downloads
* Add bare torrent hash:
I'm guessing sometimes users need the torrent hash
(magnet_uri only shows up when no torrent is available)
lambda is probably not the best way to go,
again, wasn't sure - to add a function just for this, to add it in the torrent model, to add a function to `torrents.py`?
~I've seen several RSS feeds that use `CDATA` in order to avoid parsing of …
=> Update RSS template

nyaa/forms.py, nyaa/models.py, nyaa/routes.py, nyaa/templates/_formhelpers.html, nyaa/templates/edit.html, nyaa/templates/upload.html, nyaa/templates/view.html
*Edited in af0cca2:* Updated upload/edit images:
Align information & flags:
Show full category names to fill out the field:
---
See latter commit for list of changes.
Screens below:
(note: `ENFORCE_MAIN_TRACKER` is unset; the notice is not removed from templates)
----
---
=> Restructure upload edit

nyaa/forms.py, nyaa/routes.py, nyaa/templates/upload.html
And also bring back CSRF to upload form.
Since we've gotten a few spam torrents, this should be of some help.
However it breaks upload scripts which are using the /upload form.
Should probably wait until upload API v2 is merged before merging this so whoever is still using /upload can migrate to it.
=> Add ReCaptcha to upload page if user is not logged in.

.travis.yml
...So that no one will forget to adhere to PEP8 coding style.
Of course repo owners need to enable the [Travis-CI](https://github.com/integrations/travis-ci) integration for this organization/repo for it to test every commit and pull request.
Output example (of a failed lint check):
=> Auto python lint check using Travis

nyaa/routes.py, nyaa/templates/rss.xml, nyaa/templates/xmlns.html
I reworked the output of the feed generator and replaced the custom `seeders`, `leecher`, `infoHash`, `category_Id`, `category`, and `size` tags with namespace-prefixed versions to conform to RSS standard.  
To provide said namespace I added an endpoint for the URI, as well as an HTML document for information on the it.
=> Changed RSS feed to conform to RSS standards and added a namespace

nyaa/models.py, nyaa/routes.py, nyaa/templates/layout.html, nyaa/templates/search_results.html, nyaa/templates/user.html, nyaa/templates/view.html
PR for image previews.
Fixes #174 
Torrent hash on torrent pages:
Searching for a hex representation of a hash as the sole input (eg. `5c39cf8ba80757a409d51bdacffab644f8a4960e`) will redirect to the torrent, if found:
(RSS or user page searches are not redirected)
Search field placeholder will show "Search for <user>'s torrents":
=> Info hash search, hash on torrent page, template adjustments

nyaa/routes.py, nyaa/static/js/main.js, nyaa/templates/view.html
PR for posterity (and images, we all love images)
This will use the functionality provided in `main.js` that is used for the torrent age title/local date in the listing and pages, for comments. Ie. the timestamp title and inner text are generated clientside during `DOMContentLoaded`. This means the ages will not get out of sync when cached pages are served to the user.
=> Calculate comment age clientside

nyaa/forms.py, nyaa/static/js/main.js, nyaa/templates/_formhelpers.html, nyaa/templates/layout.html, nyaa/templates/view.html
As stated in #215, the Commonmark implementation we use is strictly commonmark and lacks (mostly) tables.
This PR replaces Commonmark with [markdown-it](https://github.com/markdown-it/markdown-it) and adds some CSS-fixes to the tables.
Elements tagged with `markdown-text` are parsed and rendered on `DOMContentLoaded` instead of separate `<script>` tags for every element (most notably with comments).
Preview:
Also escapes the description markdown in the editor just as is done on the torrent page (Cloudflare strips empty lines and in the editor, whitespaces is prepended to the lines)
=> Move to markdown-it

nyaa/static/css/main.css, nyaa/templates/help.html
And so the spoonfeeding begins.
It includes little anchors over headings that you can click to link your one reading-challenged friend to the right section.
In the future, adding an explanation of the different categories and labels under a new h2 would be a good thing.
=> Get started with a bare-bones help page

nyaa/templates/edit.html
Small nitpick change.
"Edit" being the button that saves the edits might be a little confusing, whereas "Save Changes" is less ambiguous and more easily recognised.
=> Change label of button on edit page from "Edit" to "Save Changes"

nyaa/templates/view.html
A small convenience change which by sets the focus to the newly opened modal dialog's text field if the report button is hit.
This way, people can type away their gripes with the torrent without having to click into the text field first.
Not sure if this is the cleanest way to add some more JS for this.
=> Focus report reason text field when reporting

migrations/versions/3001f79b7722_add_torrents.uploader_ip.py, nyaa/api_handler.py, utils/api_info.py, utils/api_info_v2.py
Added API Info query.
As close to API Upload v2 behavior as possible.
=> API Info v2

nyaa/api_handler.py, utils/api_info.py
And a tiny bit of the serverside endpoint.
`-h`:
```
usage: api_info.py [-h] [-s] [-u USER] [-p PASSWORD] [--host HOST] [--raw]
[-m]
HASH_OR_ID
Query torrent info on Nyaa.si
optional arguments:
-h, --help            show this help message and exit
Connection options:
-s, --sukebei         Query torrent info on sukebei.Nyaa.si
-u USER, --user USER  Username or email
-p PASSWORD, --password PASSWORD
Password
--host HOST           Select another api host (for debugging purposes)
Response options:
--raw                 Print only raw response (JSON)
-m, --magnet          Print magnet uri
Required arguments:
HASH_OR_ID            Torrent ID or hash (hex, 40 characters) to query for
You may also provide environment variables NYAA_API_HOST, NYAA_API_USERNAME
and NYAA_API_PASSWORD for connection …
```
=> Clean up info api script

es_mapping.yml, nyaa/search.py
For #205.
*Note:* This obviously changes the ES schema and requires a re-indexing.
```
This fixes searching for "Machiavellianism", 16 chars ("Machiavellianis", 15 chars, worked previously).
Does not (seem to!) break anything, but requires a re-indexing of ES.
```
=> Multi-field search display_name to match words over ngram limit

nyaa/static/css/main.css, nyaa/templates/layout.html
As per suggested in #116, the search bar is reordered. I personally also find this order more intuitive.
=> Issue #116: Reordering of the search bar

nyaa/static/css/main.css
This way it looks better and more clear.
=> Setting height for comment textarea

run.py
Without a shebang, the shell tries to interpret the file as a shell script if you issue the `./run.py` command; setting `chmod +x` on the file without a proper shebang is useless.
=> Add proper shebang line to run.py

nyaa/static/css/main.css, nyaa/templates/reports.html, nyaa/templates/view.html
A bunch of small mostly styling changes, affecting reports and the report list.
* A small warning is added to the report modal to tell people that they should only report things that actually break the rules. Not sure if this will help, but it's worth a try.
* The reports list styling has been made more pleasant and usable.
* Extra information has been added to the reports list, such as whether the reporter is trusted, whether the uploader is trusted, the name of the uploader, and (for superadmins only) the uploader IP.
* Responsive tables blow ass.
New reports list look.
And this is how it looks like if you narrow your browser window; getting rid of the `table-responsive` means that you can actually see the action column without scrolling if the reason is long.
=> Frontend report improvements

.gitignore, .travis.yml, README.md, nyaa/routes.py, nyaa/utils.py, tests/__init__.py, tests/test_api_handler.py, tests/test_backend.py, tests/test_bencode.py, tests/test_filters.py, tests/test_utils.py
Other than the changes to the rfc822 filters and the rename of the (unused) `flattenDict` function,
the changes are mostly contained in the `tests` folder.
***
* Make rfc822 filters compatible with Windows systems.
> `.strftime()` is relative to the system it's being run on.
> UNIX has `%s` for seconds since the EPOCH, Windows doesn't (raises `ValueError`).
> Solution: use `.timestamp()` to achieve the same result on both/all platforms.
> This also allows us to drop the float() around it, since it returns a float.
[Docs for datetime.timestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp)
* I also took the opportunity to add tests for some of the filters in `routes.py`
* Changed `rfc822_es` filter's function name in order to be able to test it separately. …
=> Fix RFC822 filters + More tests

nyaa/templates/help.html
We're spoon-feeding people this information. Might as well go all the way.
=> Add links to torrent clients' download pages

nyaa/routes.py, nyaa/templates/layout.html, nyaa/templates/rss.xml, nyaa/templates/view.html, nyaa/views/__init__.py, nyaa/views/site.py, setup.cfg
* Start sorting imports (one by one for now) - `isort path/to/file.py` (requires [`isort`](https://pypi.python.org/pypi/isort) to be installed in virtual environment)
* Start restructuring the `routes.py` file into smaller blueprint files.
This is a suggestion... There might be a better way to go about this.
Starting small, with the static routes:
* /about (commented out)
* /help
* /rules
* /xmlns/nyaa
=> [Restructure routes 1] Import sorting + Static pages

nyaa/routes.py
Attempted fix for #288 as suggested in https://github.com/nyaadevs/nyaa/issues/288#issuecomment-316606724
- Change disposition from inline to attachment
- Add Content-Length header (by updating `_get_cached_torrent_file`)
P.S.
I wish `<class 'werkzeug.datastructures.Headers'>` had an update method like normal dictionaries...
=> Update torrent download route headers

nyaa/routes.py, nyaa/templates/layout.html, nyaa/views/__init__.py, nyaa/views/account.py
[2nd pull request out of 8 in total]
This PR moves the following routes into the `account` blueprint (`nyaa/views/account.py`):
* /login
* /logout
* /register
* /profile
`url_for()`-s in templates were updated,
and unused imports were removed from `routes.py`.
This also moves the following related functions/methods into the blueprint:
* `redirect_url()`
* `send_verification_email()`
Notes:
* `import config` was wrong. All usages of this import were changed to `app.config` (as it is throughout the application). It was only used by the email verification stuff.
* `@app.before_request` function uses the `logout()` route function, so the call was [changed to `views.account.logout()`](https://github.com/nyaadevs/nyaa/pull/292/files#diff-ac …
=> [Restructure routes 2] Move account routes into blueprint

nyaa/routes.py, nyaa/templates/layout.html, nyaa/views/__init__.py, nyaa/views/admin.py
[3rd pull request out of 8 in total]
This PR moves the following routes into the `admin` blueprint (`nyaa/views/admin.py`):
* /reports
* /adminlog
`url_for()`-s in templates and routes were updated.
These are pretty straight-forward because they are relatively new.
***
You can also use git blame to see what code was actually changed by me (and what was plainly copied)
```console
git blame -C HEAD -- nyaa/views/admin.py
```
=> [Restructure routes 3] Move admin routes into blueprint

nyaa/routes.py, nyaa/search.py, nyaa/templates/adminlog.html, nyaa/templates/edit.html, nyaa/templates/layout.html, nyaa/templates/reports.html, nyaa/templates/search_results.html, nyaa/templates/view.html, nyaa/utils.py, nyaa/views/__init__.py, nyaa/views/account.py, nyaa/views/admin.py, nyaa/views/users.py
[4th pull request out of 8 in total]
This PR moves the following routes into the `users` blueprint (`nyaa/views/users.py`):
* /user/`<user_name>`
* /user/activate/`<payload>`
`url_for()`-s in templates and routes were updated.
This moves supporting functions and variables into other files:
* Into `nyaa.utils`:
- `cached_function()`
- `chain_get()`
* Into `nyaa.search`:
- `DEFAULT_MAX_SEARCH_RESULT`
- `DEFAULT_PER_PAGE`
- `SERACH_PAGINATE_DISPLAY_MSG`
- `_generate_query_string`
* Into the blueprint `nyaa.views.users`:
- `get_serializer()`
- `get_activation_link()`
**Notes:**
Some changes made to the master branch (https://github.com/nyaadevs/nyaa/commit/b51045503deab41e5db27caec725c9cd4b9c2f98) are not in this branch (to keep things …
=> [Restructure routes 4] Move user routes into blueprint

nyaa/templates/upload.html
This changes the tracker announce URL message to be one of those bootstrap alert bubbles, and adds an additional warning which tells people to read the rules and not upload off-topic crap.
May not be to your liking since it takes up some space.
=> upload page: use alerts, add alert about rules

nyaa/api_handler.py, nyaa/routes.py, nyaa/templates/layout.html, nyaa/templates/rss.xml, nyaa/templates/search_results.html, nyaa/templates/view.html, nyaa/views/__init__.py, nyaa/views/main.py
[6th pull request out of 8 in total]
5. Move template filters and globals into blueprint
6. << This PR >>
7. Move torrent routes into blueprint
8. Finish routes.py restructuring process, apply isort and flake8 to package.
This PR moves the following routes into the `main` blueprint (`nyaa/views/main.py`):
* `/`
* `/rss` (alias for `/?page=rss`)
`url_for()`-s in templates and routes were updated.
This also moves the following into the blueprint:
- Related functions/methods:
* `render_rss()`
- App handlers:
* `before_request()`
* `not_found()` (404 error handler)
**Even though this might seem like a big diff**,
most of the code from `routes.py` was copied **in full** into the blueprint.
The only change was to `before_request()` and …
=> [Restructure routes 6] Move home, RSS and request handlers into blueprint

nyaa/api_handler.py, nyaa/backend.py, nyaa/routes.py, nyaa/templates/edit.html, nyaa/templates/layout.html, nyaa/templates/reports.html, nyaa/templates/rss.xml, nyaa/templates/search_results.html, nyaa/templates/view.html, nyaa/views/__init__.py, nyaa/views/admin.py, nyaa/views/main.py, nyaa/views/torrents.py
[7th pull request out of 8 in total]
6. Move home, RSS and request handlers into blueprint
7. << This PR >>
8. Finish routes.py restructuring process
This PR moves the following routes into the `torrents` blueprint (`nyaa/views/torrents.py`):
* `/upload`
* `/view/<int:torrent_id>`
* `/view/<int:torrent_id>/edit`
* `/view/<int:torrent_id>/magnet`
* `/download/<int:torrent_id>.torrent` (+ alias: `/view/<int:torrent_id>/torrent`)
* `/view/<int:torrent_id>/submit_report`
* `/view/<int:torrent_id>/comment/<int:comment_id>/delete`
`url_for()`-s in templates and routes were updated.
This also moves supporting methods/functions into other files:
* Into `nyaa.backend`:
- `get_category_id_map()`
* Into the blueprint `nyaa.views.torrents`:
- …
=> [Restructure routes 7] Move torrent routes into blueprint

nyaa/routes.py, nyaa/template_utils.py, nyaa/views/__init__.py, tests/test_template_utils.py
[8th pull request out of 8 in total]
7. Move torrent routes into blueprint
8. << This PR >>
Changes in this PR:
- Move the remaining template_global - `category_name`
into 'template-utils' blueprint (`nyaa/template_utils.py`)
Function code remains unchanged apart from replacing single quotes.
- Refactor routes.py in preparation for next steps (app factory)
- Add `register()` method (`nyaa/views/__init__.py`)
- Import and register blueprints using top-level statements (`nyaa/routes.py`)
- Remove unused variable: `DEBUG_API`
- This also updates the import line in the `tests/test_template_utils.py` file, so the tests could still pass.
=> [Restructure routes 8] Finish routes.py restructuring process

migrations/versions/ffd23e570f92_add_is_webseed_to_trackers.py, nyaa/backend.py, nyaa/forms.py, nyaa/models.py, nyaa/torrents.py
***Note:*** contains schema changes (adds column `Trackers.is_webseed`)
Fixes #302
Adds webseed support ([BEP-19](http://www.bittorrent.org/beps/bep_0019.html)):
* Alembic migration for schema
* validating & storing webseeds on upload
* adjusts `.torrent` metadata generation
* fetch trackers and webseeds at the same time and separate them
The `Trackers` table is used to store both announce urls and webseeds, separated by the `is_webseed` field. This way we can still use `TorrentTrackersBase` for the relations and avoid clutter.
Tested & working.
=> [DB Schema change] Webseed support

.travis.yml, README.md, dev.py, lint.sh, requirements.txt, setup.cfg
:heavy_check_mark: Tested.
~Still not sure if I should merge `fix`/`autolint` and `isort` commands~
* Fix some more lint/import sorting issues
* Add a new tool to replace `lint.sh` (only deprecated, still works):
```
Nyaa Development Helper
=======================
Usage: ./dev.py command [different arguments]
Command can be one of the following:
lint | check       : do a lint check (flake8 + flake8-isort)
fix  | autolint    : try and auto-fix lint (autopep8)
isort              : fix import sorting (isort)
test | pytest      : run tests (pytest)
help | -h | --help : show this help and exit
You may pass different arguments to the script that is being run.
For example: dev.py test tests/ --verbose
```
=> Nyaa development helper (tool)

config.example.py, nyaa/api_handler.py, nyaa/backend.py, nyaa/views/torrents.py
`MINIMUM_ANONYMOUS_TORRENT_SIZE` can be used to require a minimum total size of torrents uploaded by anonymous users (ie. without accounts) to cut down on spam.
As growing the original upload form validator too big is unreasonable, this PR also prepares for various "advanced" validations, such as blacklisting extensions per torrent category. In this post-WTForms context we have clean access to the database as well.
Torrents will be validated just before the final `session.commit()`, and any code calling `backend.handle_torrent_upload` should prepare for raised `TorrentExtraValidationException`s.
Any errors in the new validator will be added to the form, meshing nicely with the current error display:
=> Minimum size for user-less anonymous torrents (+ post-WTForms validation)

nyaa/static/css/main.css
changes include lighter text in navbar and these:
(1st: `:visited`, 2nd: deleted, 3rd: `:visited` again, 4th: comment bubble)
ideas how to make deleted entries look non-shit are appreciated
=> Improve dark theme (2)

config.example.py, nyaa/templates/layout.html, nyaa/views/__init__.py, nyaa/views/account.py, nyaa/views/main.py, nyaa/views/users.py
```
Disables all POSTs, optionally allowing users to log in (without updating last login date)
Blocked POSTs will redirect to the GET endpoint if possible, otherwise to referrer or in last case, home page.
API requests will get a plaintext message with 405 status code.
```
Every page will display a warning about the maintenance mode.
POSTs will get a redirect and `flask.flash()`
=> Read-only maintenance mode

nyaa/templates/view.html, nyaa/views/torrents.py
Previously, people couldn't quite tell you needed to give a report reason. Now we disable the submit button until there is a reason, and flask.flash() if someone manages to submit an empty reason anyway.
=> Disable report button on empty reason

config.example.py, nyaa/forms.py, nyaa/models.py, nyaa/templates/upload.html
This PR will require accounts less than 7 days old to pass a recaptcha when uploading.
(API uploads will also be disabled, as the filed can't be filled out)
`config.example.py` is also reorganized; only configuration-change however is the addition of `ACCOUNT_RECAPTCHA_AGE`.
=> [Config change] Require recaptcha of new uploaders

config.example.py, nyaa/email.py, nyaa/templates/email/verify.html, nyaa/templates/email/verify.txt, nyaa/views/account.py, nyaa/views/users.py, requirements.txt
This PR includes a fixed-up email system with a generic `EmailHolder` class to allow different backends (eg. SMTP, various providers) to send email.
Emails are Jinja2 templated and are sent in plaintext + HTML.
Only inactive accounts are allowed to be activated, and users are immediately logged in during activation.
`config.example.py` change summary:
Adds `GLOBAL_SITE_NAME` to be used in emails
Adds mail backend selection `MAIL_BACKEND`
Adds Mailgun configuration (API base and key)
Images:
*Email*
*After clicking link*
=> [Config change] Email verification (+ Mailgun backend)

config.example.py, nyaa/email.py, nyaa/forms.py, nyaa/templates/email/reset-request.html, nyaa/templates/email/reset-request.txt, nyaa/templates/email/reset.html, nyaa/templates/email/reset.txt, nyaa/templates/login.html, nyaa/templates/password_reset.html, nyaa/templates/password_reset_request.html, nyaa/views/account.py, nyaa/views/users.py
**Depends on #380!** See the changes of this PR alone [here](https://github.com/nyaadevs/nyaa/compare/email...password-reset)
Closes #44 
Adds password recovery by email, includes a link on login page, etc.
Adds a new `config.py` entry: `ALLOW_PASSWORD_RESET`
----
*Link on login page*
*Reset request form*
*Flash*
*Sent email*
*Reset form*
*After reset*
*Reset notification email*
=> [Config change] Password reset by email

nyaa/views/account.py
This tells users who are banned the reason that they are banned, and doesn't show the same message for inactive users.
IP banned users are still just shown the boring 403 page.
=> Explicitly tell users they were banned

config.example.py, nyaa/backend.py, nyaa/forms.py, nyaa/static/js/main.js, nyaa/template_utils.py, nyaa/templates/upload.html, nyaa/utils.py, nyaa/views/torrents.py
Adds the following to config.py:
```py
RATELIMIT_UPLOADS = True
MAX_UPLOAD_BURST = 5
UPLOAD_BURST_DURATION = 45 * 60
UPLOAD_TIMEOUT = 15 * 60
```
In other words, non-trusted (includes anonymous) users may upload 5 torrents in 45 minutes, after which they will have to wait 15 minutes between uploads.
Waiting until you have less than five uploads within the previous 45 minutes, the upload page message will go away.
----
Users are shown a message on the upload page if they're being ratelimited:
Trying to upload while ratelimited will turn the dialog red:
Waiting out the 15 minutes (but still with 5 or more uploads within 45 minutes):
----
***Edit:*** Show torrents uploaded within ratelimit duration:
=> [Config change] Upload ratelimit for non-trusted uploaders

nyaa/backend.py, nyaa/forms.py, nyaa/templates/user.html, nyaa/views/users.py
This deletes and bans all torrents of a specific user.
A current caveat is that it will delete both sukebei and nyaa torrents, but will only leave a log entry in the current flavour's log.
Also did some bootstrap untangling on the user view page.
Please review these changes carefully, it's my first time messing with the DB, and I did not check whether it sends the ban command to the tracker properly.
Also, we may want to restrict nuking to only supermods.
=> Implement torrent nuking ability for mods

nyaa/static/js/compat.js, nyaa/templates/layout.html
Before bootstrap-select is loaded, a small JS piece replaces the class for the pickers with the appropriate bootstrap-select classes.
If there is no JS, the dropdowns will stay as form-control.
Obviously it doesn't look as fancy but it's better than being broken. E.g. this is how it looks like without JS in Firefox (note that FF somehow decides to mix in my system's dark theme, so it looks a bit weird):
=> Fix filter dropdowns if JS is disabled

nyaa/views/torrents.py
People could delete their own comments on torrents other than the one the URL would indicate, which meant they could mess with the total comment count on a torrent by having it be higher than it actually is through repeatedly posting and deleting comments that way.
However, they could only ever delete their own comments, so this isn't a huge issue in the first place.
=> comments: fix small lack of validation

nyaa/views/torrents.py
Only allow moderators to download torrent files that are deleted.
=> torrents: don't allow download of deleted torrents

nyaa/template_utils.py
sloppy coding on #406 
seems like pop will throw an exception if the key is not there unless we pass a default value
=> Fix keyError from pop

nyaa/torrents.py, trackers.txt
> With all trackers.txt trackers being included in generated .torrents, we can now be certain the magnet (which use trackers.txt) and the .torrent uses will not be split up in different swarms in case the main announce dies.
>(That is, if uploaders added enough of their own trackers and additional trackers were deemed unnecessary (at least 5 already), the magnet and .torrent would only share the main site announce)
Also `# comments in trackers.txt wow`
=> Remove tracker limit and always add our trackers

nyaa/templates/login.html
Fixes issue with password managers (e.g. KeePass) tabbing to 'Forgot your password?' link instead of password field.
=> Add tabindexes to login elements

config.example.py, nyaa/templates/register.html
Because reading warnings is overrated.
This does not fix people using custom domains, but it's more likely they'll know what's up when their email is thrown into the void.
Fixes #437.
=> Improve and tidy up email blacklist regexes (Hotmail)

nyaa/static/css/main.css, nyaa/templates/reports.html
I opted for `table-responsive` since the other option was to duplicate a CSS rule already present in bootstrap dark, this PR does that instead.
=> Undo responsive table for reports

nyaa/views/torrents.py
If users kept their page open for a while before reporting a torrent, and mods got it in the meantime, users could still submit reports for that torrent. This is silly and really doesn't need to happen.
=> Don't submit reports for already banned torrents

nyaa/forms.py, nyaa/templates/user.html, nyaa/utils.py, nyaa/views/users.py
This started out as a simple rebase, but then I rebased the wrong branches and it all got confusing, so here it is as a new dank commit.
We now have an `@admin_only` decorator, and we ask for confirmation before we nuke. We can also see the nuke button when users are banned, and nuking is a separate endpoint with a separate form.
Additionally, it now uses the new tracker API.
=> Redo nuke functionality

nyaa/static/js/main.js
I currently don't differentiate between "trusted" markdown and untrusted, but this should be good enough. Basically tells the browser not to send a referrer, and (not sure if relevant here) not to expose a window opener object. Also tells search engines that the link is not endorsed with "nofollow".
=> Add some rel attributes to links inside markdown

nyaa/backend.py, nyaa/forms.py, nyaa/models.py, nyaa/templates/edit.html, nyaa/templates/help.html, nyaa/templates/view.html, nyaa/views/torrents.py
This adds a new flags to torrents, which is only editable by moderators and admins. If checked, it does not allow unprivileged users to post, edit or delete comments on that torrent.
Here's what it looks like when a comment thread is locked:
What I haven't tested so far is whether all the checks still hold up when you curl pages directly, but theoretically they should.
=> Implement comment locking

nyaa/__init__.py, nyaa/templates/layout.html
By having Flask-Assets minify the two JS files we ship, namely `main.js` and `bootstrap-select.js`, we can shave off 28406 bytes.
The minified files are generated on startup. If one wishes to manually clean them up or build them, they can use the `flask assets` management command, e.g. `flask assets clean`.
=> Use Flask-Assets to minify self-hosted JS files

nyaa/templates/user.html
Hitting the cancel button does not return "", but null. Therefore the toLowerCase() fails, and throwing an exception means "sure go ahead submitting this" to JS for some godforsaken reason.
Just remove the toLowerCase for now, have people type the names properly.
=> Fix nuke button prompt

es_mapping.yml, nyaa/search.py
This PR changes the Elasticsearch mapping.
```
This commit adds a new .exact subfield to display_name, which holds a
barely-filtered version of the original title we can do "literal"
matching against. This is not real substring matching, but quoting
terms now actually does something!
Implements a simple preprocessor for the search terms to extract quoted
parts from the search terms, optionally prefixed with - to negate them.
The preprocessor will create a query that'll join all three query-types:
the simple_query_string, must-phrases and must-not-phrases.
```
tldr: quotation marks now have (more of) the expected effect now.
Also includes an optimization for the `fullword` field - don't index tokens shorter than the ngram max.
=> [ES Change] Improve Elasticsearch term quoting

nyaa/search.py, nyaa/templates/help.html
This does *not* change the mappings, no need to re-index anything.
```
Implements handling "foo"|"bar" literal OR groups in the Elasticsearch
term preprocessor. Groups can be negated with -, but don't mesh with
precedence (like plain literals).
This is a partial hack, the real solution would be to parse the entire
search terms ourselves, with AND and OR groups, negations etc. But
having that work neatly with the simple_query_string would be bit of a
hassle.
```
Also updates `help.html` with clearer info on quoting search terms.
Fixes #474.
=> [ES] Improve search term preprocessing to include literal groups

es_mapping.yml
```
Before, long.tokens.with.dots.or.dashes would get edgengrammed up to the
ngram limit, so we'd get to long.tokens.wit which would then be split -
discarding "with.dots.or.dashes" completely. The fullword index would
keep the complete large token, but without any ngramming, so incomplete
searches (like "tokens") would not match it, only the full token.
Now, we split words before ngramming them, so the main index will
properly handle words up to the ngram limit. The fullword index will
still handle the longer words for non-ngram matching.
Also optimized away duplicate tokens from the indices (since we rely on
boolean matching, not scoring) to save a couple megabytes of space.
```
=> [ES Change] Delimit words before ngram, optimize tokens

nyaa/forms.py, nyaa/models.py, nyaa/templates/user.html, nyaa/views/users.py
Moderators can press this button on inactive users to manually activate their accounts.
Furthermore, the admin form code has been refactored a bit, reducing some code duplication.
=> user page: add manual activation button for mods

es_mapping.yml, nyaa/templates/help.html
```
...by splitting input into characters, instead of whitespace delimited
words. This means you can now match partial words, real substrings from
anywhere: "foo ba" will match "Foo Bar Baz", while previously you had to
have full words ("foo bar") to match anything.
My dev setup incurred an 8% increase in storage usage, from ~13MB to
~14MB (for ~40k torrents).
Small change, big improvement. Wonder why I didn't do this at first.
```
Requires re-indexing Elasticsearch.
=> [ES Change] Implement real substring matching

nyaa/views/users.py
Now uses flask.flash to give the person who clicks it feedback when it's clicked, because caching may make things confusing.
Also only activate a user if they're inactive, as again, caching can lead to staff pressing the button multiple times in a row, leading to unnecessary log messages.
=> users: activation button improvements

config.example.py, nyaa/__init__.py, nyaa/models.py
The first commit adds an option `ENABLE_GRAVATAR`, which can be disabled to have flask always serve the default avatar URL. This is useful in situations where gravatar cannot reach the host nyaa is running on, e.g. if you're developing behind a firewall.
The second commit pre-generates the default URL if `SERVER_NAME` is set, which saves one `url_for` call per shown avatar. On my machine, a `url_for` takes about 0.3 ms, so in a 300 comment shitfest I'd shave off 90 ms in this situation.
Whether or not `SERVER_NAME` is set depends on how the application is run, so I'm not sure whether this works in production.
=> [Config Change] Various Gravatar-related changes

nyaa/__init__.py, nyaa/extensions.py, nyaa/models.py, requirements.txt
Using Flask-Caching, we can memoize the `magnet_uri` method. Here, a timeout of 1 hour is chosen, though that value can be fiddled with.
The cache is defined in `extensions.py`, but gets initialised in `__init__.py`.
=> Add 1 hour cache to magnet URIs

nyaa/static/js/main.js, nyaa/templates/home.html, nyaa/templates/infobubble.html, nyaa/templates/infobubble_content.html
Infobubble text is now in a separate file, along with a timestamp, so that changes to it don't result in merge conflicts too often.
We also add some JS to make the bubble dismissible, keeping track of the last timestamp that was dismissed in localstorage.
I'm not entirely sure if I'm happy with the "HTML inside template variable" approach. If someone has a better idea, let me know. This is a bit of a ghetto setup until we have an announcement blog or something that does this in the database.
=> Make blue info bubble dismissible, configurable

config.example.py, nyaa/forms.py, requirements.txt
```
Adds a new config entry (EMAIL_SERVER_BLACKLIST, tuple of IPv4 addresses
as strings) and an email validator for registering, which will query all
the MX records for the domain and reject the registration if any of the
A records for any of the MX records are found in the blacklist.
If the query fails, the blacklist is ignored; the email is accepted.
```
This also adds `dnspython` as a requirement; run `pip install -r requirements.txt`
=> [Config change] Allow blacklisting email servers by IP

requirements.txt
Apparently, when running things with Python 3.7, these three dependencies ran into build issues with a renamed struct field.
Upgrading them seems to fix the issue, and hopefully keeps them working with Python 3.6 as well.
=> requirements: update dependencies for newer python

trackers.txt
Leechers Paradise shut down yesterday: https://torrentfreak.com/huge-torrent-tracker-calls-it-quits-after-12-years-citing-article-13-181207/
No point continuing to add it to torrents.
=> Remove leechers-paradise from default trackers

nyaa/templates/search_results.html
Someone put this inside the loop despite it essentially being constant. Probably makes immeasurably little difference perf-wise, but why not fix it anyway.
=> templates: move icon_dir set outside of the loop

nyaa/templates/view.html
If a user has a comment under the edit time limit in a comment locked torrent, but also are still affected by the new account CAPTCHA cooldown, the template would throw an error as we tried to getattr on a None object (namely, the `comment_form`).
To fix this, we also need to check around the edit form whether the `comment_form` exists.
=> view: fix template throwing exception on edge case

nyaa/backend.py, nyaa/views/torrents.py, tests/test_backend.py
This commit introduces a regex to replace illegal (expectedly unused)
characters from torrent display name, information link and description
upon upload or edit.
Fixes #541
No automatic cleanup for existing possibly dirty fields, though that's easy enough to do by hand.
=> upload/edit: sanitize some string fields

nyaa/templates/view.html
Using flask-caching, we can add a 1 hour cache to the template output of a filelist, varying it by the key "filelist" + the hex infohash of a torrent.
Using a very big filelist as a test, I get a difference in page load speeds of about a magnitude. (400ms -> 37 ms)
=> templates: cache torrent view filelist

nyaa/static/js/main.js, nyaa/templates/home.html, nyaa/templates/infobubble.html, nyaa/templates/infobubble_content.html
Changes from last time:
1. `infobubble_content.html` still is a separate file, but now instead of containing variables, contains just an actual HTML template.
2. `info_ts` is now in the main infobubble ts file because otherwise our include wouldn't work.
3. Use include now so we don't have to have users duplicate their message for non-JS users.
4. Setting `info_ts` to 0 disables the bubble now.
I've rebased it onto master too, because I'm a good lad.
=> Make blue info bubble dismissible, configurable (second attempt)

nyaa/static/css/main.css, nyaa/templates/search_results.html
Avoid repeated style attributes, instead use nth-child CSS selectors and classes where appropriate.
Also, get rid of the useless `<div>` around column headings. They don't seem to do anything useful and are just more stuff for the browser's layout engine to juggle around.
=> search_results: various fixes to the DOM

nyaa/static/css/main.css, nyaa/templates/view.html
Firefox would insert a lot of weird whitespace, because its `user-select` would default to `all` and not `text`, so it copypastes the whitespace of otherwise completely invisible HTML elements.
I don't know why Firefox does this. It's stupid, and not what the user expects. They're copying what they see, not what the DOM is.
=> view.html: fix comment text copypasting in Firefox

config.example.py, migrations/versions/5cbcee17bece_add_trusted_applications.py, nyaa/forms.py, nyaa/models.py, nyaa/static/css/main.css, nyaa/static/js/main.js, nyaa/templates/_formhelpers.html, nyaa/templates/admin_trusted.html, nyaa/templates/admin_trusted_view.html, nyaa/templates/email/trusted.html, nyaa/templates/email/trusted.txt, nyaa/templates/layout.html, nyaa/templates/trusted.html, nyaa/templates/trusted_form.html, nyaa/templates/trusted_rules.html, nyaa/views/account.py, nyaa/views/admin.py, nyaa/views/site.py
This lets users apply for trusted status, given certain minimum requirements. Moderators can then review the applications, giving a recommendation, and administrators can accept or reject them.
If an application is accepted or rejected, the user receives an e-mail about it.
Markdown images are not rendered in applications to prevent browsers from sending automatic requests to untrusted webservers.
Users who have had their application rejected cannot re-apply for a set amount of days.
=> Add trusted application functionality

config.example.py, nyaa/__init__.py, nyaa/extensions.py, requirements.txt
The Flask-Caching cache can now properly be configured from the config.py, and redis caching has experimentally been tested and confirmed to be working in theory.
We also document that one may want to use CACHE_THRESHOLD to limit the maximum number of items in the simple cache.
=> Improve cache configuration

nyaa/backend.py
Users could double their ratelimit by uploading some torrents as anonymous submissions, then log into their account and post more.
We can stop this by making the filter_uploader helper function use an sqlalchemy.or_ query to check for uploads from either that user or that user's IP.
=> backend: count IP uploads in the user ratelimit

config.example.py, nyaa/views/account.py
Add a configurable cooldown in seconds for which no further accounts can be created from the same IP.
=> account: add IP rate limiting for account creation

config.example.py, nyaa/__init__.py, nyaa/extensions.py, nyaa/views/account.py, requirements.txt
This doesn't discriminate between failed logins and successful logins, but only counts POST requests. The limit is set to 6 per hour.
Please check that this works properly with any reverse-proxying configuration you may be using.
Requires installing dependency "Flask-Limiter", which has been added to requirements.txt.
=> Add login endpoint rate limiting

config.example.py, nyaa/search.py, nyaa/views/main.py, nyaa/views/users.py
```
SQA's baked queries prepares the queries in advance, caching yada yada.
Makes thing a bit faster.
Also bigger speedup included is a shoddy cache for the total torrent
count (only applied to baked queries currently). Caching the value for a
few dozen seconds shaves off some wasted time, as it's mostly just used
for pagination.
```
Yeah yeah, get baked, ha ha.
Simple benchmarks
```
Before baked
Page   1: min: 59.0ms max: 72.9ms avg: 67.1ms
Page   2: min: 56.2ms max: 97.6ms avg: 66.1ms
Page   3: min: 60.1ms max: 92.4ms avg: 69.3ms
Page   4: min: 59.9ms max: 88.0ms avg: 68.8ms
Page   5: min: 60.1ms max: 90.9ms avg: 67.1ms
With baked (no count cache, COUNT_CACHE_DURATION=0)
Page   1: min: 56.6ms max: 69.2ms avg: 61.8ms
Page   2: min: 51.0ms max: 75.5ms avg: 62.1ms
Page   3: min: 52.8ms …
```
=> Introduce baked queries

nyaa/models.py, nyaa/torrents.py
```
with our trusty tool: caching!
```
Turns out the old cache.memoize wasn't doing much at all. Implement working caching for the magnet uri generation.
Bench
```
Before patch
Page   1: min: 59.0ms max: 72.9ms avg: 67.1ms
Page   2: min: 56.2ms max: 97.6ms avg: 66.1ms
Page   3: min: 60.1ms max: 92.4ms avg: 69.3ms
Page   4: min: 59.9ms max: 88.0ms avg: 68.8ms
Page   5: min: 60.1ms max: 90.9ms avg: 67.1ms
With patch
Page   1: min: 42.0ms max: 57.5ms avg: 50.1ms
Page   2: min: 44.9ms max: 61.4ms avg: 50.7ms
Page   3: min: 43.9ms max: 64.1ms avg: 50.1ms
Page   4: min: 45.9ms max: 62.2ms avg: 52.4ms
Page   5: min: 45.6ms max: 76.2ms avg: 53.4ms
With patch + baked + count cache
Page   1: min: 27.3ms max: 36.6ms avg: 30.0ms
Page   2: min: 25.8ms max: 40.0ms avg: 29.4ms
Page   3: min: 25.3ms max: …
```
=> Optimize magnet generation
